### ISSUE TITLE
Support DuckDB as a SQL Client

### ISSUE THREAD

**Issue by rexledesma** [transform-data/metricflow#103]
**Describe the Feature**
DuckDB is basically the SQLite equivalent of OLAP databases. This would be great if you want an embeddable metrics layer in your product. You wouldn't need to manage an external server, don't need to manage a separate installation, support for denormalized tables, etc. 

**Would you like to contribute?**
Perhaps.

**Anything Else?**
https://duckdb.org/

**Comment by tlento** [comment]
This has been released! Thanks @plypaul !
