### ISSUE TITLE
CLI MF Infer Inference solver could not determine a type for this column

### ISSUE THREAD

**Issue by edlouth** [transform-data/metricflow#204]
**Describe the bug**
When running `mf infer` against a snowflake database we get lots of FIXMEs like:
```
# FIXME: company_name
#   - Inference solver could not determine a type for this column
```

**Expected behavior**
Would expect these columns to appear as dimensions

**Environment (please complete the following information):**

- MetricFlow CLI Version 0.111.0

**Comment by tlento** [comment]
Interesting. Based on that name, yes, I agree, but the inference for dimensions is mostly driven by distributional attributes and things like column types. I have two hypotheses:

1. Something about those columns in your snowflake DB are causing them to fall through to unknown in the inference engine, like maybe a type we aren't accounting for (or maybe a bug in our type matching logic).
2. The default confidence filter is too high, and so a lot of things we think are "maybe dimensions" are getting unclassified

@edlouth Two questions:

1. Are there common column types for these fields? Or are they all VARCHAR?
2. Do you get better results if you pass `--solver-threshold 0.5`?

@serramatutu is there an easy way for a user to get a log stream of the inference choices and how things were chosen? I don't see anything in the CLI but I know the API can do this.

**Comment by edlouth** [comment]
1. All these columns are typed as `VARCHAR(16777216)` in Snowflake
2. I ran infer with `--solver-threshold 0.6` and there was no improvement

If it helps at all we get lots of rows like this in the `requirements.txt` file

```
  company_name
    type: UNKNOWN
    reasons:  -- 
    problems: 
    - Inference solver could not determine a type for this column
 ```

**Comment by tlento** [comment]
@edlouth thanks for the info, that problem output and typing info is very helpful. @serramatutu is looking into this so I expect we'll have a fix soon.

**Comment by tlento** [comment]
@edlouth we released the attached improvement for this last week (in `v0.111.1`). Hopefully this improves things for you. 

I'll leave this open for a bit longer in case you're still hitting the same issue. Please do let us know if this is working better for you!
