### ISSUE TITLE
MetricFlow should know that dbt knows about metrics

### ISSUE THREAD

**Issue by nhandel** [transform-data/metricflow#266]
**Describe the Feature**

[dbt metrics](https://docs.getdbt.com/docs/building-a-dbt-project/metrics) users should be able to use MetricFlow to build metrics queries. To do this, MetricFlow should be able to parse dbt metrics configs and build a Metricflow model. That model would then provide all the same interfaces that it does today (list metrics, get dimension values, query, materializations, etc.)

**Context** 

dbt is a popular data transformation framework with support for metric definitions. dbt metrics are new, but there is growing interest in the space, and MetricFlow should be able to support users of dbt natively. 

This feature would enable anyone using dbt metrics to use Metricflow as an interface to their metrics and transform as a self-serve BI tool without additional configuration.

**Requirements**

The happy product flow would look like this:

1. Connect to a dbt repo with dbt metrics
    1. The first version is just a way to query metrics from a dbt model using MetricFlow to keep things simple.
    2. MetricFlow parses dbt metrics into a MetricFlow model object, and then MetricFlow does everything as it would on a MetricFlow model.
2. Users can run all of the same MetricFlow commands just like they would for any other metric defined using MetricFlow’s config spec.

This flow would require the following new features in MetricFlow.

1. [P0] A new dbt metrics Parser [See details below]
2. [P1] Model updates to support count metric type(rather than sum, metrics as an input to expr metrics, a new meta parameter, and making owners optional
3. [P1] Validations would need some updates to run on a dbt metrics constructed model.
4. [P2] We should probably add a testing suite at some point that runs dbt metrics and Metricflow on the same dbt metrics spec and validates that we are keeping MetricFlow in sync to any dbt metrics changes.

**Parser Proposal**

There are some logic mapping decisions here, but it’s mostly pretty straightforward. I’m open to feedback!

1. Read in dbt metrics from YAML to a simple dbt metric object.
2. Build Data Sources - Use dbt metrics objects to generate data source MetricFlow objects, but do not write out new YAML. This is not conversion. It’s just reading from dbt metrics.
    1. Make data sources of type `sql_table`.
    2. Add a reference to the `dbt_model` param so that Transform/users building on MetricFlow could connect to dbt Cloud metadata and lineage. 
    3. Unfortunately, there are no identifiers, so there would be no joins.
    4. Collect all dimensions that are in the set of metrics built from a dbt model and generate dimensions from them
        1. Dimensions - Take all dimensions and filters and make them dimensions—Deduplicate between different metrics.
        2. Time - Use the most common timestamp for a set of metrics built on a data source and make that the primary time. Other timestamps should be secondary.
            1. If the timestamp is not the primary time, use a secondary time in the measure used to construct that dbt metric.
    5. Collect all metrics and build measures from the `expression` and `calculation_method` fields in dbt
        1. All metrics except the `expr` metric-type should be measure_proxy metrics. They should use `create_metric: true` unless they have a dbt metric filter.
        2. The `derived`  dbt metric-type maps to an `expression`  MetricFlow metric and doesn’t require adding measures to the data source.
3. Build metrics off of the constructed data source objects
    1. For each metric, build a metric object.
    2. The [dbt metric properties](https://docs.getdbt.com/docs/building-a-dbt-project/metrics) below could be mapped into the metric object, as shown below.
    
**dbt metrics -> MetricFlow mapping**
```
name -> metric[name] & data_source[measure[name]]
model -> data_source[name] & data_source[sql_table] & data_source[dbt_model]
label -> metric[display_name]
calculation_method -> if calculation_method = `derived` then metric[type] else data_source[measures[agg]]
expression -> data_source[measures[expr]]
timestamp -> data_source[dimensions]
time_grains -> None
dimensions -> data_source[dimensions]
filters -> data_source[dimensions]
meta -> metric[meta]
```

**Would you like to contribute?**

I’m happy to help with design and product requirements!

**Anything Else?**

Let’s make metrics useful for all wherever they are defined!

**Comment by nhandel** [comment]
https://github.com/transform-data/metricflow/pull/279

**Comment by QMalcolm** [comment]
I think we closed this early, #279 only merged into the feature-branch for this issue. However, the feature branch is about to be opened as a PR.

**Comment by tlento** [comment]
@QMalcolm we good to close this or do we have a few other features to roll out here?

**Comment by QMalcolm** [comment]
We have some bugs to follow up on and some things to finalize, but this can be considered closed. The core functionality is there 🎉
