### ISSUE TITLE
Whitespace in metric-names causing errors in the tutorial

### ISSUE THREAD

**Issue by callum-mcdata** [transform-data/metricflow#347]
**Describe the bug**
When going through the tutorial, I ran into a bug with the following command `mf list-dimensions --metric-names 'new_customers, transactions'` which is listed out on [this page of the tutorial.](https://docs.transform.co/docs/metricflow/metricflow-tutorial). The error appears to be the single whitespace before the `transactions` metric causing the following error:

```
⠸ 🔍 Looking for all available dimensions...
ERROR: Unknown metric: MetricReference(element_name=' transactions') in element set
Log file: /Users/callummccann/.metricflow/logs/metricflow.log
```

I was able to resolve this by removing the whitespace. So I suspect the fix is either adding whitespace removal to that command _or_ removing that whitespace in the tutorial documentation!

**Steps To Reproduce**
Walk through the tutorial and reach that step. More information about my particular set up in the environment section.

**Expected behavior**
I expected the command to return the list of shared dimensions between the two metrics as per the documentation.

**Environment (please complete the following information):**
- mf 0.130.1
- duck-db

**Comment by vvlu603** [comment]
Hi Callum, 

Thank you for flagging this! We've updated the tutorial accordingly to remove the white space. 

As always, we're happy to see comments/feature requests/contiburionts for MetricFlow.
