### ISSUE TITLE
Multi-metric output does not join on NULL values

### ISSUE THREAD

**Issue by tlento** [transform-data/metricflow#363]
**Describe the bug**
The current behavior of our multi-metric query output is to do a FULL OUTER JOIN on all dimensions. So if we have `some_nullabool` as our dimension, with the values TRUE, FALSE, and NULL, we can see output like:

```
m1, m2, some_nullabool
25, 17, TRUE
91, 22, FALSE
18, NULL, NULL
NULL, 36, NULL
```

This is hews to standard SQL NULL semantics - where NULL values are not comparable because they represent an unknown - but breaks human expectations.

This is made more problematic because it prevents sensible pivots for downstream customers. If we wanted to reshape this data like so:

```
metric, some_nullabool_is_true, some_nullabool_is_false, some_nullabool_is_null
m1, 25, 91, 18
m2, 17, 22, 36
```

the pivot logic would have to manage the NULL coalesce across rows, which is an external dependency on logical output that's best avoided.

**Steps To Reproduce**

1. Run a query with multiple metrics and a dimension that contains NULL values

**Expected behavior**
MetricFlow is a framework for allowing humans to make sense of data, and to apply a certain level of consistency in how people consume and process metric output. We should favor the more human approach of coalescing the nulls and putting the metric values on the same row in that case, so people can see that as `unknown` and interpret the comparison accordingly.

**Comment by nhandel** [comment]
This is my understanding!
