### ISSUE TITLE
Validation methods should not return Optional collections of errors

### ISSUE THREAD

**Issue by tlento** [transform-data/metricflow#49]
**Describe the bug**
We have validation methods that return objects containing Optional collections of issues and things of that nature. In particular, the ModelBuildResult has an optional "issues" tuple which gets populated with a tuple of validation errors whenever validation runs. Making this optional leads to callsite shenanigans like this:

```
errors = ModelValidator.validate_model.issues or tuple()
```

It's a small thing but it has cascading effects, where we need to do None type checks or coalesces all over the place.

**Expected behavior**
 It'd be more natural to have the return type be a required collection (i.e., a Tuple rather than an Optional[Tuple]).

This will require some restructuring, since the ModelValidator.validate_model function returns a ModelBuildResult, and the ModelBuildResult class is currently overloaded to return a model built by parsing input YAML, which might or might not have been validated. Using None as an implicit indicator of whether or not validation has occurred is not desirable. We should either have an explicit flag or, better still, we should divide up ModelBuildResult into ModelParsingResult and ModelValidationResult.

**Environment (please complete the following information):**

- MetricFlow Version [e.g. 1.0.0]

**Comment by yanghua** [comment]
> It'd be more natural to have the return type be a required collection (i.e., a Tuple rather than an Optional[Tuple]).

It seems the basic fix has been implemented in [this commit](https://github.com/transform-data/metricflow/commit/8228ca39399fae2246d277cc5c397cd290215be2). Right?

> better still, we should divide up ModelBuildResult into ModelParsingResult and ModelValidationResult

Do we still need this solution? @tlento

**Comment by tlento** [comment]
> It seems the basic fix has been implemented in [this commit](https://github.com/transform-data/metricflow/commit/8228ca39399fae2246d277cc5c397cd290215be2). Right?

Yes, thanks for finding that.

I think we can live without splitting up the ModelBuildResult for now, so I'll close this out.
