### ISSUE TITLE
Typo in displayed command.

### ISSUE THREAD

**Issue by AlessandroLollo** [transform-data/metricflow#56]
https://github.com/transform-data/metricflow/blob/883081b951ed1abf8b5446e0552101254d94793e/metricflow/cli/main.py#L142

The displayed command should be `mf query --metrics transactions --dimensions ds --order ds --explain --display-plans`

**Comment by vvlu603** [comment]
Closing, the command + tutorial were fixed in both of the merges -- thank you!
