### ISSUE TITLE
Create a MetricFlow client by passing the absolute path of the config file

### ISSUE THREAD

**Issue by AlessandroLollo** [transform-data/metricflow#57]
**Describe the Feature**
It would be useful to be able to create a MetricFlow client by passing the path of the configuration file.
If the path of the config file is not provided, then fallback on the default config file.

Right now we can do:
```
mf_client = MetricFlowClient.from_config() # config file must be in ~/.metricflow/config.yaml
```

It would be useful to be able to do also:
```
path = "/path/to/my/config/file.yaml"
mf_client = MetricFlowClient.from_config(path)
```

**Would you like to contribute?**
I can try 😅

**Comment by AlessandroLollo** [comment]
Just realized that the path can be configured via an environment variable, so I'm not sure this issue is really necessary.

**Comment by WilliamDee** [comment]
Hey Alessandro!
Ya, this is definitely configurable via an environment variable, but I also realized that you made an excellent point as allowing a user to pass in a path to a config will make it much more flexible. Fortunately, it is a very simple change, I opened a PR here https://github.com/transform-data/metricflow/pull/61 feel free to take a look!

**Comment by WilliamDee** [comment]
Done in #61
