### ISSUE TITLE
README is way too complex

### ISSUE THREAD

**Issue by tpennypacker** [transform-data/metricflow#8]
It took two experienced developers 10 minutes of close reading to figure out what you actually do. The first line of the readme should accurately convey to the layman what the product does in its simplest form.

Example:
## Welcome to MetricFlow
We create SQL queries that you can reuse.

**Comment by vishnuravi** [comment]
I think including a real-world example would go a long way to making the README easier to understand.

**Comment by tlento** [comment]
Agree we need a more direct opening, and we're working on a simple example as well. Thanks for the input!

**Comment by tlento** [comment]
#7 adds an opening which should address the core of this issue. Feedback welcome! 

Also, filed #20 about the real world examples, because I think that merits separate discussion.

**Comment by vishnuravi** [comment]
> #7 adds an opening which should address the core of this issue. Feedback welcome!

The opening is very clear now, thank you for addressing this so quickly!
