### ISSUE TITLE
Simplify Time Constraint SQL

### ISSUE THREAD

**Issue by tlento** [transform-data/metricflow#9]
**Describe the bug**
Time Constraints are rendered in SQL as follows:

```
WHERE (
  subq_166.ds >= CAST('2022-02-26' AS TIMESTAMP)
) AND (
  subq_166.ds <= CAST('2022-03-28' AS TIMESTAMP)
)
```

Change them to:
```
WHERE
  subq_166.ds BETWEEN CAST('2022-02-26' AS TIMESTAMP) AND CAST('2022-03-28' AS TIMESTAMP)
```

**Comment by patclrk** [comment]
This project is awesome! Looking to contribute by taking a crack at this issue. 

I've got the SQL working but I broke many of the integration tests. It looks like these tests are pulling from `snapshots`. Changing the `.sql` files for each SqlClient seems straightforward but I'm not sure about the `.xml` files. Are the `.xml` files generated somewhere?

Cheers!

**Comment by tlento** [comment]
Hi @patclrk , thanks for diving in!

Those .xml files are generated (as are the .sql files). In theory you should be able to regenerate all snapshot files by running this command:

`poetry run pytest --overwrite-snapshots metricflow/tests`

Then you can commit those changes and add them to your PR. I typically have all plans change in the same commit with the thing that modified them so I don't have broken tests in the middle of the PR, but sometimes that gets too crazy.

I've also taken the liberty of assigning this issue to you, but feel free to put it back up for grabs if you find you don't have the time to keep going.

**Comment by tlento** [comment]
Also you'll need to run the tests once per SQL client type (SQLite, Redshift, Snowflake, BigQuery). If you don't have access to all of those let us know and we'll work out a way to provide you with a patch for the plan files.
